name: Delete Artifacts

on:
  workflow_dispatch: 

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch artifact list and delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          ARTIFACTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts)

          # Find the artifact ID for 'artifacts'
          ARTIFACT_ID=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name=="my-artifact") | .id')

          # Delete the artifact if it exists
          if [ -n "$ARTIFACT_ID" ]; then
            curl -X DELETE \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
            echo "Artifact deleted: my-artifact"
          else
            echo "No artifact named 'my-artifact' found."
          fi
